/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Pin_RedLED.h"
#include "Pin_RedLED_aliases.h"
#include "CapSense.h"
#include "CapSense_CSHL.h"
#include "CapSense_MBX.h"
#include "CapSense_TunerHelper.h"
#include "CapSense_SMS.h"
#include "CapSense_PVT.h"
#include "CapSense_IP.h"
#include "Pin_GreenLED.h"
#include "Pin_GreenLED_aliases.h"
#include "PWM.h"
#include "Clock.h"
#include "EZI2C_1.h"
#include "EZI2C_1_PINS.h"
#include "EZI2C_1_PVT.h"
#include "EZI2C_1_EZI2C.h"
#include "EZI2C_1_EZI2C_PVT.h"
#include "EZI2C_1_BOOT.h"
#include "RC_OUT.h"
#include "RC1.h"
#include "RC1_aliases.h"
#include "CapSense_SampleClk.h"
#include "CapSense_Sns_aliases.h"
#include "CapSense_SenseClk.h"
#include "EZI2C_1_SCBCLK.h"
#include "EZI2C_1_sda.h"
#include "EZI2C_1_sda_aliases.h"
#include "EZI2C_1_scl.h"
#include "EZI2C_1_scl_aliases.h"
#include "EZI2C_1_SCB_IRQ.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "cy_em_eeprom.h"
#include "CyLFClk.h"

/*[]*/

